#!/bin/bash

PROG_NAME=`basename $0`;
HASH_PROG=md5sum;

if [ $# -ne 2 ]; then
    echo "ERROR: Incorrect number of arguments";
    echo "Usage: ${PROG_NAME} directory register_file";
    exit 1;
fi

DIR_NAME=$1;
REGISTRY_FILE=$2;

[ -f ${REGISTRY_FILE} ] && truncate -s 0 ${REGISTRY_FILE};

IFS=$'\n';
for i in `find ${DIR_NAME}`; do
    [ -f "${i}" ] && $HASH_PROG "${i}" >> ${REGISTRY_FILE};
done
unset IFS;
