#!/bin/bash

generate_html_header () {
  local readonly FILE_NAME=$1;
  local readonly TITLE=$2;

  if [ -z "${FILE_NAME}" -o -z "${TITLE}" ]; then
    echo "ERROR: Invalid number of arguments.";
    return 1;
  fi

  echo "<html>" > ${FILE_NAME};
  echo "<head><title>${TITLE}</title></head>" >> ${FILE_NAME};
  echo "<body>" >> ${FILE_NAME};

  return 0;
} #generate_index_header


generate_html_footer () {
  local readonly FILE_NAME=$1;

  if [ -z "${FILE_NAME}" ]; then
    echo "ERROR: Invalid number of arguments.";
    return 1;
  fi

  echo "</body>" >> ${FILE_NAME};
  echo "</html>" >> ${FILE_NAME};

  return 0;
} #generate_index_header



readonly PROG_NAME=`basename $0`;
if [ $# -ne 3 ]; then
  echo "ERROR: Incorrect number of arguments";
  echo "Usage: ${PROG_NAME} register_file_1 registry_file_2 output_dir";
  exit 1;
fi

readonly REGISTRY_FILE_1=$1;
readonly REGISTRY_FILE_2=$2;
readonly OUTPUT_DIR=$3;
if [ -d ${OUTPUT_DIR} ]; then
  echo "Output directory already exists, do you want to empty it?";
  read ANSWER;
  if [ "${ANSWER}" == "y" -o "${ANSWER}" == "Y" ]; then
    rm -r ${OUTPUT_DIR};
  else
    exit 0;
  fi
fi

mkdir ${OUTPUT_DIR};
readonly INDEX_FILE="${OUTPUT_DIR}/index.html";

generate_html_header $INDEX_FILE 'full_index';


SAME_REGISTRY='false';
N_LINES=0;
if [ "${REGISTRY_FILE_1}" == "${REGISTRY_FILE_2}" ]; then
  readonly SAME_REGISTRY='true';
  N_LINES=1;
fi
readonly N_LINES;

IFS=$'\n';
for i in `cat ${REGISTRY_FILE_1}`; do
  MD5=`echo $i | awk '{print $1}'`;
  HTML_ENTRY_EXISTS=`cat ${INDEX_FILE} | grep ${MD5}`;
  if [ -z ${HTML_ENTRY_EXISTS} ]; then
    DUP_LINE=`cat ${REGISTRY_FILE_2} | grep ^${MD5} | sed -e "s/\n/foo/g"`
    DUP_FOUND=`echo "${DUP_LINE}" | wc -l`;
    if [ ${DUP_FOUND} -gt ${N_LINES} ]; then
      DUPE_HTML_FILE=${OUTPUT_DIR}/${MD5}.html;
      generate_html_header ${DUPE_HTML_FILE} ${MD5};
      if [ "${SAME_REGISTRY}" != 'true' ]; then
        echo "${i}" > ${DUPE_HTML_FILE};
      fi
      for j in ${DUP_LINE}; do
        FILE_LINK=`echo ${j} | awk '{$1=""; print $0}'`
        echo "<br><a href='${FILE_LINK}'>${FILE_LINK}</a></br>" >> ${DUPE_HTML_FILE};
      done
      generate_html_footer ${DUPE_HTML_FILE} ${MD5};
      echo "<br><a href='${MD5}.html'>${MD5}</a></br>" >> ${INDEX_FILE};
    fi
  fi
done
unset IFS;

generate_html_footer $INDEX_FILE 'full_index';
exit 0;
